In [1]:
import nltk
from nltk.corpus import wordnet

nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\devanshu\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\devanshu\AppData\Roaming\nltk_data...

True

In [3]:
words = [
    "car",
    "bank",
    "bat",
    "dog",
    "light",
    "plant",
    "book",
    "teacher",
    "student",
    "computer"
]

In [4]:
for word in words:
    print("\nWord:", word)

    synsets = wordnet.synsets(word)

    for syn in synsets[:3]:
        print("Synset:", syn.name())
        print("Definition:", syn.definition())

        if syn.examples():
            print("Example:", syn.examples()[0])
        else:
            print("Example: No example available")

Word: car
Synset: car.n.01
Definition: a motor vehicle with four wheels; usually propelled by an internal combustion engine
Example: he needs a car to get to work
Synset: car.n.02
Definition: a wheeled vehicle adapted to the rails of railroad
Example: three cars had jumped the rails
Synset: car.n.03
Definition: the compartment that is suspended from an airship and that carries personnel and the cargo and the power plant
Example: No example available

Word: bank
Synset: bank.n.01
Definition: sloping land (especially the slope beside a body of water)
Example: they pulled the canoe up on the bank
Synset: depository_financial_institution.n.01
Definition: a financial institution that accepts deposits and channels the money into lending activities
Example: he cashed a check at the bank
Synset: bank.n.03
Definition: a long ridge or pile
Example: a huge bank of earth

Word: bat
Synset: bat.n.01
Definition: nocturnal mouselike mammal with forelimbs modified to form membranous wings and anatomical adaptations for echolocation by which they navigate
Example: No example available
Synset: bat.n.02
Definition: (baseball) a turn trying to get a hit
Example: he was at bat when it happened
Synset: squash_racket.n.01
Definition: a small racket with a long handle used for playing squash
Example: No example available

Word: dog
Synset: dog.n.01
Definition: a member of the genus Canis (probably descended from the common wolf) that has been domesticated by man since prehistoric times; occurs in many breeds
Example: the dog barked all night
Synset: frump.n.01
Definition: a dull unattractive unpleasant girl or woman
Example: she got a reputation as a frump
Synset: dog.n.03
Definition: informal term for a man
Example: you lucky dog

Word: light
Synset: light.n.01
Definition: (physics) electromagnetic radiation that can produce a visual sensation
Example: the light was filtered through a soft glass window
Synset: light.n.02
Definition: any device serving as a source of illumination
Example: he stopped the car and turned off the lights
Synset: light.n.03
Definition: a particular perspective or aspect of a situation
Example: although he saw it in a different light, he still did not understand

Word: plant
Synset: plant.n.01
Definition: buildings for carrying on industrial labor
Example: they built a large plant to manufacture automobiles
Synset: plant.n.02
Definition: (botany) a living organism lacking the power of locomotion
Example: No example available
Synset: plant.n.03
Definition: an actor situated in the audience whose acting is rehearsed but seems spontaneous to the audience
Example: No example available

Word: book
Synset: book.n.01
Definition: a written work or composition that has been published (printed on pages bound together)
Example: I am reading a good book on economics
Synset: book.n.02
Definition: physical objects consisting of a number of pages bound together
Example: he used a large book as a doorstop
Synset: record.n.05
Definition: a compilation of the known facts regarding something or someone
Example: Al Smith used to say, `Let's look at the record'

Word: teacher
Synset: teacher.n.01
Definition: a person whose occupation is teaching
Example: No example available
Synset: teacher.n.02
Definition: a personified abstraction that teaches
Example: books were his teachers

Word: student
Synset: student.n.01
Definition: a learner who is enrolled in an educational institution
Example: No example available
Synset: scholar.n.01
Definition: a learned person (especially in the humanities); someone who by long study has gained mastery in one or more disciplines
Example: No example available

Word: computer
Synset: computer.n.01
Definition: a machine for performing calculations automatically
Example: No example available
Synset: calculator.n.01
Definition: an expert at calculation (or at operating calculating machines)
Example: No example available

In [5]:
print("Words with multiple meanings:\n")

for word in words:
    synsets = wordnet.synsets(word)

    if len(synsets) > 1:
        print(word, "has", len(synsets), "meanings")

Words with multiple meanings:

car has 5 meanings
bank has 18 meanings
bat has 10 meanings
dog has 8 meanings
light has 47 meanings
plant has 10 meanings
book has 15 meanings
teacher has 2 meanings
student has 2 meanings
computer has 2 meanings

In [6]:
for word in ["bank", "bat", "light"]:
    print("\n", word.upper())

    for syn in wordnet.synsets(word)[:5]:
        print(syn.name(), ":", syn.definition())

 BANK
bank.n.01 : sloping land (especially the slope beside a body of water)
depository_financial_institution.n.01 : a financial institution that accepts deposits and channels the money into lending activities
bank.n.03 : a long ridge or pile
bank.n.04 : an arrangement of similar objects in a row or in tiers
bank.n.05 : a supply or stock held in reserve for future use (especially in emergencies)

 BAT
bat.n.01 : nocturnal mouselike mammal with forelimbs modified to form membranous wings and anatomical adaptations for echolocation by which they navigate
bat.n.02 : (baseball) a turn trying to get a hit
squash_racket.n.01 : a small racket with a long handle used for playing squash
cricket_bat.n.01 : the club used in playing cricket
bat.n.05 : a club used for hitting a ball in various games

 LIGHT
light.n.01 : (physics) electromagnetic radiation that can produce a visual sensation
light.n.02 : any device serving as a source of illumination
light.n.03 : a particular perspective or aspect of a situation
luminosity.n.01 : the quality of being luminous; emitting or reflecting light
light.n.05 : an illuminated area

In [7]:
import pandas as pd
from nltk.corpus import wordnet

In [9]:
words = [
    "dog",
    "cat",
    "car",
    "apple",
    "teacher",
    "student",
    "computer",
    "bird",
    "rose",
    "school"
]

In [10]:
data = []

for word in words:

    synsets = wordnet.synsets(word, pos=wordnet.NOUN)

    if synsets:
        syn = synsets[0]
        hypernyms = syn.hypernyms()

        if hypernyms:
            hypernym = hypernyms[0].name()
        else:
            hypernym = "None"

        data.append([word, syn.name(), hypernym])

df = pd.DataFrame(
    data,
    columns=["Word", "Synset", "Direct Hypernym"]
)

df

       Word         Synset               Direct Hypernym
0       dog       dog.n.01          domestic_animal.n.01
1       cat       cat.n.01                   feline.n.01
2       car       car.n.01            motor_vehicle.n.01
3     apple     apple.n.01                     pome.n.01
4   teacher   teacher.n.01                 educator.n.01
5   student   student.n.01                 enrollee.n.01
6  computer  computer.n.01                  machine.n.01
7      bird      bird.n.01               vertebrate.n.01
8      rose      rose.n.01                    shrub.n.01
9    school    school.n.01  educational_institution.n.01

In [11]:
words = ["dog", "cat", "car", "bird", "rose"]

In [12]:
for word in words:

    synsets = wordnet.synsets(word, pos=wordnet.NOUN)

    if synsets:
        syn = synsets[0]

        print("\n", word)

        for i in range(3):
            print("Level", i, ":", syn.name())

            hypernyms = syn.hypernyms()

            if not hypernyms:
                break

            syn = hypernyms[0]

 dog
Level 0 : dog.n.01
Level 1 : domestic_animal.n.01
Level 2 : animal.n.01

 cat
Level 0 : cat.n.01
Level 1 : feline.n.01
Level 2 : carnivore.n.01

 car
Level 0 : car.n.01
Level 1 : motor_vehicle.n.01
Level 2 : self-propelled_vehicle.n.01

 bird
Level 0 : bird.n.01
Level 1 : vertebrate.n.01
Level 2 : chordate.n.01

 rose
Level 0 : rose.n.01
Level 1 : shrub.n.01
Level 2 : woody_plant.n.01

In [13]:
pairs = [
    ("car", "automobile"),
    ("dog", "cat"),
    ("dog", "animal"),
    ("dog", "computer"),
    ("car", "bus"),
    ("teacher", "student"),
    ("apple", "orange"),
    ("computer", "banana")
]

In [14]:
results = []

for word1, word2 in pairs:

    syn1 = wordnet.synsets(word1, pos=wordnet.NOUN)[0]
    syn2 = wordnet.synsets(word2, pos=wordnet.NOUN)[0]

    similarity = syn1.path_similarity(syn2)

    results.append([
        word1,
        word2,
        syn1.name(),
        syn2.name(),
        similarity
    ])

df = pd.DataFrame(
    results,
    columns=[
        "Word 1",
        "Word 2",
        "Synset 1",
        "Synset 2",
        "Similarity"
    ]
)

df

     Word 1      Word 2       Synset 1       Synset 2  Similarity
0       car  automobile       car.n.01       car.n.01    1.000000
1       dog         cat       dog.n.01       cat.n.01    0.200000
2       dog      animal       dog.n.01    animal.n.01    0.333333
3       dog    computer       dog.n.01  computer.n.01    0.090909
4       car         bus       car.n.01       bus.n.01    0.125000
5   teacher     student   teacher.n.01   student.n.01    0.142857
6     apple      orange     apple.n.01    orange.n.01    0.250000
7  computer      banana  computer.n.01    banana.n.01    0.083333

In [15]:
df = df.sort_values("Similarity", ascending=False)

df

     Word 1      Word 2       Synset 1       Synset 2  Similarity
0       car  automobile       car.n.01       car.n.01    1.000000
2       dog      animal       dog.n.01    animal.n.01    0.333333
6     apple      orange     apple.n.01    orange.n.01    0.250000
1       dog         cat       dog.n.01       cat.n.01    0.200000
5   teacher     student   teacher.n.01   student.n.01    0.142857
4       car         bus       car.n.01       bus.n.01    0.125000
3       dog    computer       dog.n.01  computer.n.01    0.090909
7  computer      banana  computer.n.01    banana.n.01    0.083333

In [16]:
print("Observation:")
print("Words with similar meanings have higher similarity scores.")
print("Words with unrelated meanings have lower similarity scores.")

Observation:
Words with similar meanings have higher similarity scores.
Words with unrelated meanings have lower similarity scores.

In [17]:
data = [
    ["bank",
     "I deposited money in the bank.",
     "Financial institution",
     "money, deposited"],

    ["bank",
     "We sat beside the bank of the river.",
     "Side of a river",
     "river"],

    ["bat",
     "A bat flew out of the cave.",
     "Flying mammal",
     "flew, cave"],

    ["bat",
     "He hit the ball with a bat.",
     "Sports equipment",
     "hit, ball"],

    ["bark",
     "The dog has a loud bark.",
     "Sound made by a dog",
     "dog, loud"],

    ["bark",
     "The bark of the tree was rough.",
     "Outer covering of a tree",
     "tree, rough"],

    ["light",
     "Turn on the light.",
     "Illumination",
     "turn on"],

    ["light",
     "This bag is very light.",
     "Not heavy",
     "bag"],

    ["match",
     "He lit the candle with a match.",
     "Object used to make fire",
     "candle, lit"],

    ["match",
     "The two teams played a football match.",
     "Sports game",
     "teams, football"]
]

In [18]:
df = pd.DataFrame(
    data,
    columns=[
        "Word",
        "Sentence",
        "Intended Meaning",
        "Context Clue"
    ]
)

df

,Word,Sentence,Intended Meaning,Context Clue
0,bank,I deposited money in the bank.,Financial institution,"money, deposited"
1,bank,We sat beside the bank of the river.,Side of a river,river
2,bat,A bat flew out of the cave.,Flying mammal,"flew, cave"
3,bat,He hit the ball with a bat.,Sports equipment,"hit, ball"
4,bark,The dog has a loud bark.,Sound made by a dog,"dog, loud"
5,bark,The bark of the tree was rough.,Outer covering of a tree,"tree, rough"
6,light,Turn on the light.,Illumination,turn on
7,light,This bag is very light.,Not heavy,bag
8,match,He lit the candle with a match.,Object used to make fire,"candle, lit"
9,match,The two teams played a football match.,Sports game,"teams, football"